### ISSUE TITLE
Latest version destroying battery

### ISSUE THREAD

**Issue by hbhbhbhbhbhb** [premnirmal/StockTicker#101]
Updated to latest beta this morning and it's draining battery like crazy + overheating my phone. Also the widget constantly flickers and freaks out.
I'm on a OnePlus 6, Android 9

**Comment by premnirmal** [comment]
Thank you for letting me know, I will look in to it and cut a new beta

**Comment by premnirmal** [comment]
@hbhbhbhbhbhb - fixed in this commit https://github.com/premnirmal/StockTicker/pull/100/commits/7d993ec4adefc13ff87c252016e2e9ff4d951ffe
The update will be rolled out soon
