### ISSUE TITLE
Multiple Widgets not working

### ISSUE THREAD

**Issue by newbieg** [premnirmal/StockTicker#102]
Android Version: 7.1.1
Manufacturer: Samsung
Kernel: 3.10.49
Download Source: Google Play

I really like this app. It's one of the most useful apps on my phone.
I noticed that in app settings there's a short tutorial for setting up multiple widgets on the same phone. That's a great idea so I can separate my own portfolio and a list of stocks that I'm considering but haven't bought yet. 
I followed this tutorial, and I thought I did everything right, but the second widget is never created. I think there's something broken there.

Thank you for the great app, 
Newbieg

**Comment by premnirmal** [comment]
@newbieg thanks for reporting this. Unfortunately I can't reproduce this bug - when I try to add multiple widgets they get added successfully.
Please note that for the second widget, once you add the widget it will be empty ie with no portfolio. you must manually add stocks to `widget #2` from the app via search

**Comment by newbieg** [comment]
Wow, I tried to add a widget as I was writing the description above and it did not work then or ten times before that. Maybe a recent update fixed the issue... That's confusing... Cool, it's working on my phone now, so nice...
Thanks for your time, hope I didn't waste too much of it.

**Comment by newbieg** [comment]
Ok, Found what I was doing differently while trying to add the widget. 

It works if I search and add a stock and hit the back button. -> The widget is created, stock in place.

It fails if I search and add a stock and hit the button on the keypad that says "Done" (I'm using the default softkeyboard on my phone) -> widget fails to be created, no indication that one was ever attempted.

My guess is that "Done" has the same mapping as "enter" for the search input type...

Not sure how device specific we're getting at this point...

**Comment by newbieg** [comment]
Thank you, I just got the recent update. The new interface in that section is clear and concise. Nice.
