### ISSUE TITLE
Widget doesn't appears in lineageos

### ISSUE THREAD

**Issue by logos88** [premnirmal/StockTicker#105]
Hi! I have installed the application in a LG G3 using lineageos 16, but when I open the widgets menu from the launcher this app doesn't appears as an option to choose, so I can't use the widget.

**Comment by premnirmal** [comment]
Hello @logos88 - I wonder if this is an issue with the Trebuchet launcher that comes with Lineage OS or the OS. Does the widget appear in a different third party launcher on lineage OS?

**Comment by logos88** [comment]
I have tried with Clauncher and it doesn't appear there neither. Other apps like news appear in both.

**Comment by logos88** [comment]
I found the problem. I had the app installed in the sdcard. When I have moved to the internal storage I have been able to use the widget again. Sorry to bother
