### ISSUE TITLE
show stock prices and changes in a different currency

### ISSUE THREAD

**Issue by stuart12** [premnirmal/StockTicker#107]
hello, I live in euroland so I'd like to see stock prices in euros (€). I might have Google stock, traded in dollars, and I'd like to know what this stock is worth to me in euros taking into account the dollar/euro exchange rate. This would require fetching the dollar/euro exchange rate and dividing the stock prices.  This possibility was mentioned in a comment in #22.

thanks for StockTicker!

**Comment by premnirmal** [comment]
Duplicate of #22
