### ISSUE TITLE
Suggestion: grey zeros

### ISSUE THREAD

**Issue by chaoticgoo** [premnirmal/StockTicker#110]
Thank you for this great and useful app. I get it over F-Droid and am a fan. Unfortunately that means I can't upvote/rate you in the main Android store, I discovered today. Sorry about that. I hope if doesn't reduce your inclination to work with F-Droid but I thought you should know.

I only use the app full-screen, not as a widget at all, and have a small (I hope) improvement request (or option). In my opinion, the change numbers on holdings that have not gone up should not be that bright neon green that makes a user think they're making money. 

But of course they shouldn't be red, either. Zero change is not a loss. It would greatly help me skim my long watch list of often-inactive stocks if any price or percentage change of 0 or 0% was the same grey (or gray, depending where you live) as the neutral text labels beside it.

I find myself having to "read" every set of green 0's to determine their value when, if they were grey they would be a nice buffer between the green and red ones.

Does anyone else feel the same?

**Comment by premnirmal** [comment]
That's a good point. I agree that zero change should be a 'neutral' color i.e. the regular gray.

**Comment by premnirmal** [comment]
The fix is in beta 3.6.6. It will take longer for this change to be released on f-droid - once it's stable and released to master. If you want to check out the change you can sign up and download to the beta version on google play

**Comment by chaoticgoo** [comment]
Checked it out in 3.6.6 and 3.7.2 and it's looking good, thank you!
