### ISSUE TITLE
Foreign stocks in Vienna not showing charts

### ISSUE THREAD

**Issue by nilovag** [premnirmal/StockTicker#111]
Hello,
Foreign stocks traded in Vienna market are not showing charts. Everything else works but instead of the chart, a text of "no data" is shown. Try MSFT.VI or GOOA.VI 
Other foreign markets like i.e. Milan (MSFT.MI) do work.

**Comment by premnirmal** [comment]
Unfortunately the historical data api (https://www.alphavantage.co/documentation/) does not provide this data
