### ISSUE TITLE
Itc Ltd nse stock is not showing

### ISSUE THREAD

**Issue by git-root** [premnirmal/StockTicker#117]

**Comment by premnirmal** [comment]
Does the data source show this stock?

**Comment by git-root** [comment]
Data source it self not showing if I search itc or itc ltd

**Comment by premnirmal** [comment]
Then this is a bug with the data source (yahoo finance)

**Comment by git-root** [comment]
Sorry, I misunderstood ur previous question .
It is showing in Yahoo finance.

**Comment by premnirmal** [comment]
Does the yahoo finance api return it?

**Comment by git-root** [comment]
I am not sure. I am an user of this ticker currently. Thought to let you
know the issue.

**Comment by premnirmal** [comment]
Ok, thanks
