### ISSUE TITLE
graphs of stock indices

### ISSUE THREAD

**Issue by sake0815** [premnirmal/StockTicker#144]
I can happily see all stock graphs for different stocks but can't for any stock indices.

Canyou please fix it?!

cheers 
Sake

**Comment by premnirmal** [comment]
This is because of the chart source, if the source does not provide data then the app cannot show it

**Comment by sake0815** [comment]
Hi,

being more specific the S&P500 index ^GSPC does have data. At least when I look on the yahoo finance website. And also the current value is displayed correctly inside the app!?

All whats missing is the data history (month, quater, year and so on)

**Comment by premnirmal** [comment]
Got it, they will be showing in the latest build (3.9.6 and 3.9.7). The build where ^GSPC is not showing uses the alphavantage api, which we no longer use from version 3.9.6 onwards
