### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [premnirmal/StockTicker#145]
...remove DOS newlines from https://github.com/premnirmal/StockTicker/blob/master/gradle/wrapper/gradle-wrapper.properties

Ref: https://f-droid.org/wiki/index.php?title=com.github.premnirmal.tickerwidget/lastbuild_396&oldid=273192

@Bubu @eighthave so this is soooo fixed yet not really?

**Comment by premnirmal** [comment]
Thanks for reporting this, Can you open a PR to fix this? If not I can fix it later this weekend.

Is the `^M` newline character the reason f-droid builds are failing?

**Comment by licaon-kter** [comment]
@premnirmal The github web editor can't do this, no.

**Comment by premnirmal** [comment]
What is the error? I only see one line saying `ERROR: Could not build app com.github.premnirmal.tickerwidget: Error cleaning com.github.premnirmal.tickerwidget:3.9.703` in https://f-droid.org/wiki/page/com.github.premnirmal.tickerwidget/lastbuild_300900703. Nothing related to the "DOS newlines"

**Comment by licaon-kter** [comment]
Nothing written there about newlines, yes, but the issue is what I've written. :)

**Comment by premnirmal** [comment]
Seems like an issue with the f-droid build system, it should handle apps that are written in windows (that have the gradle.properties file auto updated by android studio on windows)

**Comment by licaon-kter** [comment]
Yes, it is... :) at the same time it's odd to have random files with different types, right?

**Comment by eighthave** [comment]
Windows files should be supported, but none the core fdroid devs are using Windows, so we might miss cases now and then.  Please file bugs when you find issues!  I have a fix for this coming in a merge requst.

**Comment by eighthave** [comment]
https://gitlab.com/fdroid/fdroidserver/-/merge_requests/778

**Comment by premnirmal** [comment]
Thank you @eighthave !

**Comment by premnirmal** [comment]
Looks like the build is still failing for f-droid https://f-droid.org/wiki/page/com.github.premnirmal.tickerwidget/lastbuild

Any ideas?

**Comment by licaon-kter** [comment]
@premnirmal Yes, `buildserverid: e659a5353dea91bf964585c68bf35a9314ec0656` means "before the fix", hence we wait for a buildserver update...
