### ISSUE TITLE
Translation update

### ISSUE THREAD

**Issue by jurgen178** [premnirmal/StockTicker#149]
Hi @premnirmal, in 3.9.704, change the settings text for German from
"Benachrichtigungsbenachrichtigungen erhalten - Benachrichtigungsbenachrichtigungen"
to
"Benachrichtigungen erhalten - Legt fest ob Benachrichtigungen erhalten werden."
And in the release update, change 
"- Fehler beheben" 
to 
"- Fehler behoben"

**Comment by premnirmal** [comment]
Thank you @jurgen178. Fixed in 404232b938e3ab3f7f34e189a1344f62a2bc9467 (3.9.705)
