### ISSUE TITLE
Prive data not updating

### ISSUE THREAD

**Issue by kevster666** [premnirmal/StockTicker#154]
For 0p0000ru7w.l the historical chart shows correct price data, but the daily price is stuck.

**Comment by premnirmal** [comment]
Data is fetched from yahoo finance, so if prices are not incorrect that's an issue with yahoo finale

**Comment by kevster666** [comment]
No - historic data shows the correct prices, but live price is wrong. So the correct price data is in there somewhere but not being updated correctly? Or blsme Yahoo and wash hands of any responsibility...
