### ISSUE TITLE
Crypto Assets Fail To Load

### ISSUE THREAD

**Issue by GravyPouch** [premnirmal/StockTicker#171]
When trying to add a crypto asset (ex: BTC) to my portfolio an error appears saying failed to fetch data. The crypto is added to my portfolio but it does not display a price and it blank. I do not know if this is a glitch or not. I really hope this is just a bug because I would love to add my crypto assets to this app. Thank you guys I really appreciate what your making here.
![btcfailstoload](https://user-images.githubusercontent.com/29843812/102565999-90091900-40ac-11eb-9667-a54a334f6788.jpeg)

**Comment by b0bdN** [comment]
Hi @GravyPouch,

You have to write the symbol to obtain the data of the cryptocurrency market.
For exemple:
Bitcoin USD -> **BTC-USD**
![StockTicker_BTC](https://user-images.githubusercontent.com/23734573/102680357-6258c880-41af-11eb-9441-efe580ee152f.png)

Monero USD -> **XMR-USD**
![StockTicker_XMR](https://user-images.githubusercontent.com/23734573/102680360-64228c00-41af-11eb-9777-39796b7fd056.png)

**Comment by GravyPouch** [comment]
> Hi @GravyPouch,
> 
> You have to write the symbol to obtain the data of the cryptocurrency market.
> For exemple:
> Bitcoin USD -> **BTC-USD**
> ![StockTicker_BTC](https://user-images.githubusercontent.com/23734573/102680357-6258c880-41af-11eb-9441-efe580ee152f.png)
> 
> Monero USD -> **XMR-USD**
> ![StockTicker_XMR](https://user-images.githubusercontent.com/23734573/102680360-64228c00-41af-11eb-9777-39796b7fd056.png)

Thank you so much
