### ISSUE TITLE
1D Range - Display hours

### ISSUE THREAD

**Issue by b0bdN** [premnirmal/StockTicker#172]
Hi,

Is it possible to display the hours instead of the date in the 1 day range of the chart?

![StockTicker_1DRange_xAxis](https://user-images.githubusercontent.com/23734573/102680089-2de40d00-41ad-11eb-8751-36ba7d154a71.png)

**Comment by premnirmal** [comment]
Good point, yes that should be updated to display the hours

**Comment by b0bdN** [comment]
Do you know how to do it?
Because I tried to figure it out but I didn't find how :/

**Comment by premnirmal** [comment]
It's an axis formatter. The 1D range needs a different axis formatter (existing one: https://github.com/premnirmal/StockTicker/blob/master/app/src/main/kotlin/com/github/premnirmal/ticker/ui/AxisFormatters.kt#L17)
