### ISSUE TITLE
"Aktualisierung fehlgeschlagen" - update failed

### ISSUE THREAD

**Issue by mandavister** [premnirmal/StockTicker#186]
Out of some reason the stock price update fails sometimes on my device which probably has nothing to do with the StockTicker. (that might be related to background activity and saving battery - I'm not sure) But what's annoying is, that the longer the app was open, the more often the update might have failed. And for every failed update I get another of this modal messages "Aktualisierung fehlgeschlagen" on top. So sometimes I click very often to get them away - more often I now tend to kill the app and open it anew. But I believe one of that messages would suffice.

**Comment by petermllrr** [comment]
Same here. When pulling down to refresh it says "Failed to fetch data".

**Comment by premnirmal** [comment]
Fixed in b7c0b5287fa914077b052ceb5f9008533e3bd991
