### ISSUE TITLE
GDAXI not working

### ISSUE THREAD

**Issue by sniperle** [premnirmal/StockTicker#19]
^DJI is working fine but ^GDAXI is not working. After adding it's not shown in the list.

**Comment by premnirmal** [comment]
Thanks.. looks like google finance doesnt have GDAXI (http://finance.google.com/finance/info?client=ig&q=.GDAXI), but yahoo does (https://query.yahooapis.com/v1/public/yql?env=store://datatables.org/alltableswithkeys&format=json&q=select%20*%20from%20yahoo.finance.quotes%20where%20symbol%20in%20%28%22^GDAXI%22%29). 

Will add a fix this weekend

**Comment by sniperle** [comment]
Working now, thank you :-)
