### ISSUE TITLE
Stock price digits are cut off

### ISSUE THREAD

**Issue by rcbyron** [premnirmal/StockTicker#193]
![Screenshot_20210208-121530_1](https://user-images.githubusercontent.com/12629601/107263529-78447600-6a07-11eb-982c-d36bdfc12409.png)

Stock widget showing incorrect values for prices beyond 3 digits. See screenshot. 2080 gets shown as 080. Using a Pixel 5, app version 3.9.731 (it was working correctly in v3.9.729)

**Comment by premnirmal** [comment]
If you go into widget settings you can turn off the currency, then it should have enough space to show the correct price.

This setting is available in version 3.9.733+
