### ISSUE TITLE
Refresh failed

### ISSUE THREAD

**Issue by IanWorthington** [premnirmal/StockTicker#194]
When a number refreshes fail it seem to queue up a stack of failure message boxes, all of which need to be dismissed before getting back to the app.  I'm thinking that a single message should suffice.

I'm also thinking that an alarm be generated to alert the user if they are depending on price alarms to fire?

**Comment by wilx** [comment]
I am experiencing this as well. See attached image.
![Screenshot_20210216-165142_Stocks Widget-censored](https://user-images.githubusercontent.com/1098563/108087701-fd6b0300-7077-11eb-8ef1-d8c6e9352a6c.jpg)

**Comment by premnirmal** [comment]
The stack of error dialogs has been fixed in 26ce74f7bbd06f4612970b9423f61e46ebcecee4
