### ISSUE TITLE
StockTicker crashes when entering/searching for new tickers

### ISSUE THREAD

**Issue by sniperle** [premnirmal/StockTicker#2]
StockTicker crashes when entering/searching for new tickers.

I/ActivityManager(11128): START u0 {flg=0x10000000 cmp=com.github.premnirmal.tickerwidget/com.github.premnirmal.ticker.ui.ParanormalActivity} from pid -1
I/ActivityManager(11128): Start proc com.github.premnirmal.tickerwidget for activity com.github.premnirmal.tickerwidget/com.github.premnirmal.ticker.ui.ParanormalActivity: pid=16423 uid=10322 gids={50322, 3003, 1028, 1015}
D/ActivityThread(16423): handleBindApplication:com.github.premnirmal.tickerwidget
D/Event   (16423): No subscribers registered for event class com.github.premnirmal.ticker.events.StockUpdatedEvent
I/ActivityManager(11128): Displayed com.github.premnirmal.tickerwidget/com.github.premnirmal.ticker.ui.ParanormalActivity: +1s184ms
I/Timeline(11128): Timeline: Activity_windows_visible id: ActivityRecord{655a4868 u0 com.github.premnirmal.tickerwidget/com.github.premnirmal.ticker.ui.ParanormalActivity t61} time:93070245
I/Timeline(11128): Timeline: Activity_windows_visible id: ActivityRecord{655a4868 u0 com.github.premnirmal.tickerwidget/com.github.premnirmal.ticker.ui.ParanormalActivity t61} time:93085705
I/Timeline(16423): Timeline: Activity_launch_request id:com.github.premnirmal.tickerwidget time:93086406
I/ActivityManager(11128): START u0 {cmp=com.github.premnirmal.tickerwidget/com.github.premnirmal.ticker.ui.TickerSelectorActivity} from pid 16423
I/ActivityManager(11128): Displayed com.github.premnirmal.tickerwidget/com.github.premnirmal.ticker.ui.TickerSelectorActivity: +94ms
I/Timeline(11128): Timeline: Activity_windows_visible id: ActivityRecord{656505a8 u0 com.github.premnirmal.tickerwidget/com.github.premnirmal.ticker.ui.TickerSelectorActivity t61} time:93086832
E/AndroidRuntime(16423): Process: com.github.premnirmal.tickerwidget, PID: 16423
W/ActivityManager(11128):   Force finishing activity com.github.premnirmal.tickerwidget/com.github.premnirmal.ticker.ui.TickerSelectorActivity
W/ActivityManager(11128): Activity pause timeout for ActivityRecord{656505a8 u0 com.github.premnirmal.tickerwidget/com.github.premnirmal.ticker.ui.TickerSelectorActivity t61 f}
W/ActivityManager(11128): Activity pause timeout for ActivityRecord{655a4868 u0 com.github.premnirmal.tickerwidget/com.github.premnirmal.ticker.ui.ParanormalActivity t61}
I/WindowState(11128): WIN DEATH: Window{65b13d10 u0 com.github.premnirmal.tickerwidget/com.github.premnirmal.ticker.ui.ParanormalActivity}
I/ActivityManager(11128): Process com.github.premnirmal.tickerwidget (pid 16423) has died.
I/WindowState(11128): WIN DEATH: Window{656ac5d0 u0 com.github.premnirmal.tickerwidget/com.github.premnirmal.ticker.ui.TickerSelectorActivity}

**Comment by premnirmal** [comment]
Thanks for reporting this issue. Do you have the logs filtered by E (error) ? These logs show no thrown exception.

Also, does this happen every time? I tried to replicate this but never saw a crash.

**Comment by sniperle** [comment]
Thank also for you quick answer. Yes, this error happens every time when I try to search for new stocks. The error line is included above:

E/AndroidRuntime(16423): Process: com.github.premnirmal.tickerwidget, PID: 16423
W/ActivityManager(11128): Force finishing activity

**Comment by bparmentier** [comment]
I suppose @sniperle is using an ad blocker as I am. StockTicker can't connect to `d.yimg.com` as it is redirected to `127.0.0.1` in the hosts file.

Here is the logcat: https://gist.github.com/bparmentier/8032a1893875cf59624b

**Comment by premnirmal** [comment]
Thanks for pointing that out. That's probably it. Can you add an option in adblock to ignore requests to `d.yimg.com` and see if that works?

**Comment by bparmentier** [comment]
Added `d.yimg.com` to my whitelist. Searching for tickers is working now.

**Comment by premnirmal** [comment]
Thanks @bparmentier ! 
@sniperle are you using adblocker too?

**Comment by sniperle** [comment]
Yes you are right I'm using AdAway. Added d.yimg.com to my whitelist and now it's working.

**Comment by premnirmal** [comment]
Thanks guys, I'll add a note. Closing

**Comment by sniperle** [comment]
How about a message window if y.yimg.com is not reachable so the users knows what's the problem ?  ;-)

**Comment by premnirmal** [comment]
Added a message, closing now.
