### ISSUE TITLE
Widget resize bug

### ISSUE THREAD

**Issue by musabshak** [premnirmal/StockTicker#204]
Touching the first row of the widget (where the refresh button is located), enters the widget resize mode. This did not use to be the case. Not sure if this is a bug or an intentional feature but it is quite disruptive to the flow of using the widget. That is, everytime I touch the refresh button and slightly miss the button, the widget enters resize mode.

**Comment by xeyownt** [comment]
Ah ah, I didn't know we could resize the widget, so I uninstalled the app asap because it was 1x1.
On my phone though we get in resize mode only when moving the widget around, making it a bit less obvious.
Maybe this resizing also deserves a remark in the widget helper text.
