### ISSUE TITLE
swipe up to mess up stocks view

### ISSUE THREAD

**Issue by megabugman** [premnirmal/StockTicker#21]
simple swipe up then stocks view is duplicated.

[![Screenshot_20170408-190022.png](https://s8.postimg.org/xn16sgyhh/Screenshot_20170408-190022.png)](https://postimg.org/image/d2wctziq9/)

**Comment by premnirmal** [comment]
Thanks for reporting this issue. Fixed in https://github.com/premnirmal/StockTicker/commit/dd38b09fc43959211476106aadfaaec6a301b4f1
