### ISSUE TITLE
Remove unused widget tabs

### ISSUE THREAD

**Issue by Edwin-VC** [premnirmal/StockTicker#210]
**Describe the bug**
I love this app. But for some reason it keeps adding empty widget tabs after switching phone and uninstall/reinstall. I have 6 empty widget tabs without actual widgets after reinstalling. When I add a new widget it will create a 7th tab. I am using the Microsoft Launcher. I did check the other launcher on this Phono (Moto launcher) but the widgets are not there either to be removed. 

**To Reproduce**
1. Install Microsoft Launcher? (not sure if this is related) 
2. Install Stocks Widgets App
3. Create 1 or more widgets, tabs are created
4. Uninstall the Stocks Widget app while Widgets are still active
5. Reinstall the stocks widget app

**Expected behavior**
After uninstalling the app I expect the widgets to be removed. When reinstall the app I expect so start with a clean sheet again. No tabs in the app that cannot be reused or removed. 

**Screenshots**
![Screenshot_20210404-072046](https://user-images.githubusercontent.com/41291991/113499454-6f0eeb80-9516-11eb-9e82-5c22fff7e040.png)

**Smartphone (please complete the following information):**
 - Device: Moto G 5G Euro Specs 
 - OS: Android 10 (up to date) 
 - Browser: Edge (up to date) 

**Additional context**
Let me know what I can do to help resolve this issue.

**Comment by AlexStapleton** [comment]
I am also having this issue. Created a widget with the Everywhere Launcher app (within it's interface), but then deleted that interface. I have an empty widget #2, but no actual widget.

Device: OnePlus7Pro running Android10

**Comment by premnirmal** [comment]
Unfortunately there is no way for an app to delete a widget. If you removed the widget from the launcher but the widget didn't get removed, then that's a bug with the launcher

**Comment by webmihir** [comment]
Widget it self works fine, however each time I remove a widget and add a new one, the old ones stay in the app. This is with Google Pixel 5 default launcher. I tried clearing cache and storage for both, the stocks widget app as well as pixel launcher. However these phantom widgets always show up in the app. I even uninstalled and reinstalled the app after cleaning launcher storage with the same result.

At this point I believe this is likely a bug with the app, not the launcher.  i understand there is no programmatic way to remove a widget, however I'll appreciate if there is an option to "hide" some widgets from showing up in the app, or at least choose the default widget that opens with the app (and news feed).

**Comment by hbhbhbhbhbhb** [comment]
Same issue for me after reinstalling on a OnePlus 6, four empty widgets in the app I can't rid of.
Can we get an in app option to clean up unused widgets?

**Comment by flurbius** [comment]
This sounds like its an issue with android and/or the launchers involved.  However it could be fixed by some code to remove empty widgets.

**Comment by ZisBoom** [comment]
@premnirmal I was hoping to bump this thread.  It appears the stock ticker app is displaying multiple watchlist tabs for widgets that don't exist in any launcher.

Uninstalling and installing the app does not clear this list, nor does clearing the app's storage and cache.  
Creating a new widget creates a new tab in the watchlist, and removing that new widget via the launcher removes the associated tab - but the old ones are still stuck.  I'm fairly certain the empty phantom tabs in the watchlist came from importing a phone launcher backup.

I'll take a peek into the code to see if there may be an issue with looking in two places for widget configurations, but I'm not capable of fixing the code as I haven't done android development.  

An ideal fix would be either an option to delete all watchlist/widgets at once from a settings menu, or a long-press action on a watchlist widget tab to delete the item.  Currently long press on the tab just shows the widget name.  

Thanks for everything you've done on the app - this is the biggest usability bug for me, as it's a bunch of clutter.  Getting to the first real tab in the watchlist is getting harder and harder as the ghosts pile up.

**Comment by premnirmal** [comment]
Repeating what I said before:
The app **does not** save the widgets, the widget list comes from the OS. The app is open source, you can look at the code for yourself and you'll see that this is not an app bug.

If the app is not usable as you make it seem, then you are welcome to open a fix for this
