### ISSUE TITLE
Added Widget Gets Stuck

### ISSUE THREAD

**Issue by EstebanCardenas** [premnirmal/StockTicker#215]
**Describe the bug**
When trying to add the widget to the phone's main screen, a configuration screen appears. If the square button is pressed, the configuration screen is closed and the widget will get stuck on the home screen.

**To Reproduce**
1. Try to add a widget to the phone's home screen
2. The widget configuration screen will show up
3. Close this configuration screen (Using the overview button to see the recent apps)
4. The Widget will be stuck on the phone's different main screens
5. The Widget will disappear when an application is opened

**Expected behavior**
The Widget shouldn't be added to the phone's home screen.

**Screenshots**

![s1](https://user-images.githubusercontent.com/53832358/119214824-512e2380-ba8f-11eb-8731-3218c04d2d01.jpeg)

![s2](https://user-images.githubusercontent.com/53832358/119214831-5f7c3f80-ba8f-11eb-9d7f-74e81d7469ef.jpeg)

![s3](https://user-images.githubusercontent.com/53832358/119214833-6440f380-ba8f-11eb-87bf-2ce788467ccd.jpeg)

![s4](https://user-images.githubusercontent.com/53832358/119214837-6a36d480-ba8f-11eb-958b-7e01954f8a77.jpeg)

![s5](https://user-images.githubusercontent.com/53832358/119214840-6d31c500-ba8f-11eb-8a56-f591c5f71f68.jpeg)

**Smartphone (please complete the following information):**
 - Device: Motorola MOTO One
 - OS: Android 10
 - App Version: 3.9.738

**Comment by flurbius** [comment]
Could not reproduce this on a pixel 5 running Android 12 StockTicker v3.9775
