### ISSUE TITLE
Trackers added to app in the Play Store

### ISSUE THREAD

**Issue by user8446** [premnirmal/StockTicker#216]
Hi,
On the Play Store version you added 2 trackers: Google Firebase Analytics and Google CrashLytics. It's usually customary to not include analytics and trackers in open source apps or maybe there should be an opt-in/out setting in the app. 

I know many seek out open source for the privacy, freedom, and security and although those trackers aren't harmful some users might find it undesirable.

**Comment by premnirmal** [comment]
First of all, they are not "trackers", they are tools used to fix bugs.
If you want the version without firebase/crashlytics then download it from f-droid. If you read the readme then you will see the link to downloading from either the play store or f-droid.

**Comment by user8446** [comment]
Hi Prem,

I'm on the F-Droid version. 

I'm not debating the definitions - trackers, analytics, beacons, telemetry, data collection, or logs. I was just thinking of the everyday user on the Play Store that cares about privacy but might not have the technical knowledge to side load or use an alternative app store.

Thank you for the development!
