### ISSUE TITLE
[BUG] Update interval incorrect for 45 minutes & 1 hour

### ISSUE THREAD

**Issue by user8446** [premnirmal/StockTicker#217]
**Describe the bug**
When the update interval is set to 45 minutes, the "last fetch" and "next fetch" are set 1 hour apart. 
When the update interval is set to 1 hour, the "last fetch" and "next fetch" are set 5 minutes apart. 
Running v3.9.738

**To Reproduce**
1. Set the update interval in settings the either 45 minutes or 1 hour
2. Go to the home screen
3. Swipe down to refresh
4. Observe the incorrect last fetch and next fetch times

**Expected behavior**
The last left and next fetch should match the interval settings

Thank you

**Comment by premnirmal** [comment]
Thanks for reporting, will look into it

**Comment by premnirmal** [comment]
Fixed in e4e65cbe9996271766218ba38fd01177b6cb63fc
