### ISSUE TITLE
display local currency symbol

### ISSUE THREAD

**Issue by megabugman** [premnirmal/StockTicker#22]
dai.de is the stock ticker for Daimler listed at XETRA in Euro.
StockTicker shows Dollar instead of Euro.
This applies to other market places like Frankfurt.
The displayed currency should always correspond to the marketplace.

**Comment by StevenHachel** [comment]
Please create the possibility to display the values ​​in Euro.

**Comment by Ikosihenagon** [comment]
Any update on this issue? I have a similar issue with some ETF which are shown in GBP instead of EUR. Compared to the thread opener, the Daimler stock is shown correctly in EUR for me.

**Comment by ThomasWaldmann** [comment]
I have added "DAI.DE" to the portfolio in the app and the widget displays "70,22 EUR",  so guess this can be closed?
