### ISSUE TITLE
Error Fetching Suggestions, Can't Add New Ticker

### ISSUE THREAD

**Issue by TheOneBoris** [premnirmal/StockTicker#225]
When I try to add a new ticker symbol in the search function, I immediately get an error message saying "error fetching suggestions".  This prevents me from adding a new stock to my portfolio.

I am using a Samsung phone with the standard Android system.

Thank you!

![Screenshot_20210723-094711_Stocks Widget](https://user-images.githubusercontent.com/87864545/126791424-78832dbe-bdc4-4da8-b8c7-fb201de3b1c3.jpg)

**Comment by premnirmal** [comment]
The api is not working right now, will have to wait and see: 

https://s.yimg.com/aq/autoc?callback=YAHOO.Finance.SymbolSuggest.ssCallback&region=US&lang=en-US&query=g

**Comment by jpl-mac** [comment]
https://autoc.finance.yahoo.com/autoc?query=g&region=US&lang=en-US&guccounter=1

works, don't know if the reply format is the same

**Comment by premnirmal** [comment]
Fixed in 3.9.740

**Comment by r84r** [comment]
Please publish the .740 version on F-Droid. There the latest is still .739.

**Comment by premnirmal** [comment]
F-droid handles publishing. It is up to them to publish it on time

**Comment by premnirmal** [comment]
Alternatively you can get the latest version from the releases on the github page

**Comment by premnirmal** [comment]
> https://autoc.finance.yahoo.com/autoc?query=g&region=US&lang=en-US&guccounter=1
> 
> works, don't know if the reply format is the same

Reopening this issue, this api is also not working now

**Comment by premnirmal** [comment]
Thank you @wilx, that works. It has been fixed in v3.9.749
