### ISSUE TITLE
Unable to add a quotes

### ISSUE THREAD

**Issue by yalios** [premnirmal/StockTicker#226]
**Describe the bug**
Every time I try to enter a quote I get the message 'Error fetching suggestions ". Internet connection is good and I am able to refresh the default quotes that come when you first install the app. I have reinstall the app and have cleaned the data, but nothing.

Pixel 3a
Android 11

Thanks

**Comment by Gitbobbit** [comment]
I'm seeing the same error on Android 11. Using on different devices, Android 7 & 10, without any issues.

**Comment by mrplumber** [comment]
Can confirm this issue happens on my Nexus 5X with LineageOS (Android 8.1.0) and StockTicker v3.9.739 (F-Droid)

**Comment by yalios** [comment]
Now the app foes not open at all, it comes up with a black screen and nothing is happening.  Reinstalling resolves the black screen, but after few days it happens again.

**Comment by premnirmal** [comment]
> 
> 
> Can confirm this issue happens on my Nexus 5X with LineageOS (Android 8.1.0) and StockTicker v3.9.739 (F-Droid)

You are using an old version

**Comment by premnirmal** [comment]
This is fixed, duplicate of #225
