### ISSUE TITLE
Scroll Bar Blocks Values

### ISSUE THREAD

**Issue by stu-code** [premnirmal/StockTicker#230]
With the current version on Android 10, a scroll bar appears over stock values in the following scenarios:

- Unlocking the phone
- Opening the home sscreen where the widget is
- Touching the widget
- When the widget refreshes
- When the widget switches between prices and percentages

This issue did not occur in the prior version. Please see the attached image showing this issue.

![Screenshot_20210807-194146_Nova Launcher](https://user-images.githubusercontent.com/64608711/128616439-0237f119-19d0-45db-8554-40785dbc81e4.jpg)

**Comment by premnirmal** [comment]
Fixed in 4aabf5dba102f69852a88f974e4af708f7553af3 (v3.9.745)
