### ISSUE TITLE
Can't change to dark widgets anymore?

### ISSUE THREAD

**Issue by hbhbhbhbhbhb** [premnirmal/StockTicker#232]
After 3.9.744 update my previously black widgets went white (it's following the system theme now...).
Need an option to override this.
Changed my system them to dark, but only got the semi-dark widgets, not full black.

**Comment by IoneSect01** [comment]
Font color different

**Comment by hbhbhbhbhbhb** [comment]
Not sure why closed, still not fixed in 3.9.745
Option for solid black widget has been lost?

**Comment by IoneSect01** [comment]
Widget background now relying on app background.
App light mode, then widget light mode. 
App dark mode, then widget dark mode but font color very ugly

**Comment by IoneSect01** [comment]
Why comment is deleted?
