### ISSUE TITLE
Widget background no longer opaque after update.

### ISSUE THREAD

**Issue by blackgenie13** [premnirmal/StockTicker#233]
**Describe the bug**
I cannot change the background of my widget back to transparent after the update.  Now they are just white.

**To Reproduce**
See screenshot.

**Expected behavior**
I expect the background to be transparent like the preview and before the update.

**Screenshots**
![Screenshot_20210808-154415_One UI Home](https://user-images.githubusercontent.com/16173269/128647911-ec33aa13-7965-4c0c-bc46-7df52d2209a7.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S20
 - OS: Android 11

**Additional context**

**Comment by IoneSect01** [comment]
Font color also different
