### ISSUE TITLE
Dot as decimal separator

### ISSUE THREAD

**Issue by opk12** [premnirmal/StockTicker#236]
The dot is ignored when entering a position. `2.70` becomes `270` and the comma must be used. Dot is the common decimal separator [in about half of the world](https://en.wikipedia.org/wiki/Decimal_separator#Usage_worldwide) and on physical and smartphone calculators in the other half. This is inconvenient because it conflicts with the habit of entering the dot.

**Comment by premnirmal** [comment]
can't repro this
