### ISSUE TITLE
increase update interval

### ISSUE THREAD

**Issue by megabugman** [premnirmal/StockTicker#24]
15 min is imo to slow. i believe there a free data providers for nasdaq and othes. including an automatic realtime update would be very handy

**Comment by ThomasWaldmann** [comment]
There is a setting now that enables:
- 5mins
- 15mins
- 30mins
- 45mins
- 1hour

Not realtime, but 15mins **is** quicker update interval (which is what you meant in the issue title).

Maybe going faster would not be well-received by the data providers? If too many clients hit them with too frequent requests, that might lead to issues.
