### ISSUE TITLE
The app makes unwanted connections to Google and GitHub

### ISSUE THREAD

**Issue by ghost** [premnirmal/StockTicker#246]
**Describe the bug**
I'm using StockTicker from F-Droid. The app makes a lot of unwanted connections to Google and GitHub, which you can see on the screenshot. I use only widget and don't use financial news in the app, so why the app is doing that in background? Because widget works fine (including auto-update) with only allowed connections to Yahoo Finance, from where the app downloads stock market data. I think, this behavior is acceptable for Google Play version, but not for F-Droid version. There is even no warning on F-Droid about that the app is using proprietary services and collects data.

**To Reproduce**
1. Download and install any firewall, for example: https://github.com/M66B/NetGuard
2. Launch it, turn on and try to update stock market data through widget or restart StockTicker.
3. You probably will see aforementioned connections in the firewall.

**Expected behavior**
1. It would be great if you make the data collection opt-in (disabled by default) and add the option in the settings to enable it, if someone will want to help you.
2. It also would be great if you add the option in the settings to enable "Widget only mode" (it should disabled by default for convenient of users, they could enable it by themselves). In this mode StockTicker should make connections to Yahoo Finance only if the previous option is enabled.

**Screenshots**
![Image_0](https://user-images.githubusercontent.com/92029674/136404374-f91d63ea-30d0-4483-8722-cb9f75a305d1.jpg)

**Additional context**
Sorry, but I cut out unnecessary parts of the issue template as this issue is not related to definite version of the app or my smartphone. Anyway, thank you for the great app, the one and only FOSS stock app which is suitable for me. I hope this issue will help you to improve the app!

**Comment by premnirmal** [comment]
Fixed in 7a365c1a54859ca87c75a26cf194445308a74869, released in version 3.9.751
