### ISSUE TITLE
Dark colors with Transparent BG

### ISSUE THREAD

**Issue by swendler619** [premnirmal/StockTicker#247]
**Describe the bug**
Colors are dark red and green, inhibiting readability. 

**To Reproduce**
1. Select transparent for widget bg
2. See widget

**Expected behavior**
The previous versions that supported transparent would show the same color text as would the opaque/translucent backgrounds. 

**Screenshots**
![Screenshot_20211015-151037](https://user-images.githubusercontent.com/92605410/137548166-9d308b12-0061-4c7a-a90d-130986431643.jpg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: OnePlus 7T
 - OS: Android 11
 - Version: Oxygen OS 11.0.3.1.HD65AA

**Additional context**

**Comment by premnirmal** [comment]
What is the selected text colour option (in widget settings)?
