### ISSUE TITLE
Show Stocks in different currencies

### ISSUE THREAD

**Issue by JonasXdev** [premnirmal/StockTicker#254]
Congratulations, your app arrived in Germany! Since we don't use Dollar here, it sucks that the price is shown in dollar.

It would be great to have a feature to convert different currencies, like USD ⇿ EURO.

Another possibility is to include stocks from all over the world, but I think that is way too complicated.

**Comment by premnirmal** [comment]
It is very complicated to do the conversion because of the variable exchange rate. But the app does show quotes in different currencies depending on which exchange the quote is listed in
