### ISSUE TITLE
What's New 404 error

### ISSUE THREAD

**Issue by i13e** [premnirmal/StockTicker#268]
**Describe the bug**
Every time I open the app this message reappears with no way to turn it off that I'm aware of (downloaded from fdroid). I tried reinstalling the app, installing 770 debug from github and encountered the same issue. When installing from Google Play, the app properly displays a changelog and is then permanently dismissed.

**To Reproduce**
1. Open the app
2. See error message

**Expected behavior**
Display a what's new message or fail once and then on restart display nothing at all. A toggle to turn this feature off would probably be the easiest way to bypass this feature I imagine?
**Screenshots**
![Screenshot_20220226-192449](https://user-images.githubusercontent.com/62034540/155863559-c7b755af-6434-4fb5-935e-be169206631a.jpg)

**Smartphone (please complete the following information):**
 - Device: Oneplus 7T
 - OS: Android 11
 - App Version 3.9.768

**Comment by premnirmal** [comment]
This is fixed in the latest version, please update to 3.9.770

**Comment by git001** [comment]
Well I get the message also with the [3.9.771](https://github.com/premnirmal/StockTicker/releases/tag/3.9.771) version.

![Screenshot_20220315-122614_Stocks_Widget](https://user-images.githubusercontent.com/1579468/158368412-bff68aec-075f-4f86-ba85-abf9ef027b36.png)
