### ISSUE TITLE
F-Droid can't pick up new releases

### ISSUE THREAD

**Issue by licaon-kter** [premnirmal/StockTicker#269]
...since https://github.com/premnirmal/StockTicker/commit/d9a66be6ecc8a2ab7e2ebef30de67f5e899625ce

`app/version.properties not found in tag 3.9.770`

Ref: https://gitlab.com/fdroid/fdroiddata/-/blob/8a4dd287e9658401f2c462a1f17fc54176d45756/metadata/com.github.premnirmal.tickerwidget.yml#L1520

**Comment by premnirmal** [comment]
The version name and code is now calculated using the git tag. Is f-droid able to infer those?

**Comment by licaon-kter** [comment]
>  Is f-droid able to infer those?

Not during checkupdate, the bot is now allowed (for now) to run scripts/functions.

**Comment by premnirmal** [comment]
Is it possible to update the bot to run a script to extract the version name and code? If not I'll have to re-add the version.properties file but it'll exclusively be for f-droid and I'd rather not add a file that I may forget to update

**Comment by licaon-kter** [comment]
> Is it possible to update the bot to run a script to extract the version name and code? 

Extract from where? It was doing this until now, extracting from `app/version.properties`

> I'd rather not add a file that I may forget to update

Well then you/we/someone would need to remember to open a MR on fdroiddata to update the app.

**Comment by premnirmal** [comment]
> Extract from where? It was doing this until now, extracting from app/version.properties

From the git tag. See https://github.com/premnirmal/StockTicker/blob/master/app/build.gradle#L31 and https://github.com/premnirmal/StockTicker/blob/master/app/build.gradle#L67

**Comment by licaon-kter** [comment]
Extract =/= Run a script/functions, in my book.

Maybe you mean "calculate" :)

Like I said, no calculation, no execution.

**Comment by premnirmal** [comment]
Ok just saw the typo correction in your comment - looks like the version.properties file is the only solution for now. I will re-add that file and maintain it until f-droid can run a script to 'calculate' the version from the git tag

**Comment by premnirmal** [comment]
Added the `version.properties` file in https://github.com/premnirmal/StockTicker/commit/56a640015013788a16ca79c3abea85e98b2c3b14

Can the bot run on this head or does it need a new tag for it to execute?

**Comment by licaon-kter** [comment]
Needs a Tag
