### ISSUE TITLE
Cannot change start and end times on settings

### ISSUE THREAD

**Issue by SanPedroooo** [premnirmal/StockTicker#271]
I can't change the start and end time for the updates on the settings windows.
When I push on it the clock pops up but to close it I can only go "back" and undo the changes or touch outside of it and undo the changes.
There is no OK button to apply the changes.

**Comment by onealves** [comment]
The buttom is still there only it's invisibel though.

**Comment by premnirmal** [comment]
@SanPedroooo can you please fill in all the information for the bug including your device, android version, app version, and a screenshot?

**Comment by SanPedroooo** [comment]
@premnirmal 
Device: realme 7 pro
Android: 11 (2022.02.24 realme ui 2.0)
App: 3.9.770

@onealves is right, the button is on the botton right but it's invisible, when you push on it it becomes visible with red color.

![Screenshot_2022-03-19-15-23-51-33_2564881430859daaeae795f0b71722d1](https://user-images.githubusercontent.com/13413513/159125066-dd243873-d230-4f80-aba9-af938c5f6a96.jpg)

**Comment by premnirmal** [comment]
Fixed in https://github.com/premnirmal/StockTicker/commit/68063300d8e8ab6290f1c3e976599c7fa58c690a
