### ISSUE TITLE
Price stalled

### ISSUE THREAD

**Issue by jesuslop** [premnirmal/StockTicker#283]
The price for 0P00000WLG.F is stalled since 16/6/22, it says 34.33 but it has changed in the coming days. The fancy graph get's it OK, but the big number is wrong. Other tickers are also OK.

**Comment by premnirmal** [comment]
The price comes from yahoo finance and it is showing 34.33 as the regular market price: https://query1.finance.yahoo.com/v7/finance/quote?format=json&symbols=0P00000WLG.F

**Comment by jesuslop** [comment]
Yep. So I cannot trust Yahoo finance data for my interests. Good to know. Thanks for feedbacking quick.
