### ISSUE TITLE
buggy portfolio widget with "display currency" turned on

### ISSUE THREAD

**Issue by sans-c** [premnirmal/StockTicker#284]
**Describe the bug**
Since a few days (can't tell exactly which version introduced this) the second tab in the "portfolio" widget type is malformed if you turn "display currency" on in the widget settings.

**To Reproduce**
1. choose portfolio as your widget type
2. add some stocks
3. enable "display currency"
4. second column of the widget displays some hexadecimal garbage like ...at@c1af4d0,00 (with the 0,00 at the end being the total current value in this case)

**Expected behavior**
Show the correct value without the gibberish.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/52868970/175915236-fb5b4a9d-9977-43fe-878e-0d328aa99376.png)

**Smartphone (please complete the following information):**
 - OS: Lineage 18.1
 - App Version 3.9.785

**Additional context**
While there, maybe take a look at the "NaN". In case we just wan to monitor some stocks without actually haveing bought any, maybe just leave the field empty instead of displaying "NaN".

**Comment by premnirmal** [comment]
Fixed in b241ae2af23ee1232a07c12cb71107705da730e4
