### ISSUE TITLE
MOEX (Moscow) marketdata missing

### ISSUE THREAD

**Issue by alexxmac666** [premnirmal/StockTicker#286]
**Describe the bug**
MOEX (Moscow) marketdata missing for about a week or so.

**To Reproduce**
Try any security. GAZP.ME for example. 

**Smartphone (please complete the following information):**
 - Device: Samsung S9+
 - OS: Android 10
 - App Version - latest

**Additional context**

**Comment by alexxmac666** [comment]
anyone here?)

**Comment by premnirmal** [comment]
Data comes from yahoo finance, nothing to do with the app
