### ISSUE TITLE
Stock widget sends data to Google !!!

### ISSUE THREAD

**Issue by Grkrz** [premnirmal/StockTicker#295]
![Screenshot_20220818-224428](https://user-images.githubusercontent.com/107203983/185492657-2f91a917-8ea1-4b80-8dc7-b656168e72e7.png)
![Screenshot_20220818-224453](https://user-images.githubusercontent.com/107203983/185492686-dd764402-6d62-462f-898a-120ec0aefca7.png)

**Comment by premnirmal** [comment]
Please stop calling it a 'tracker'. We send crash reports and device info to Firebase which is owned by Google. It is a service used to capture crash reports as well as other useful info including application performance.

I recommend educating yourself before opening issues like these

**Comment by Grkrz** [comment]
Apology for starting this topic. 
You are right that I should have educated my self before accusing the app of doing something which does not do.!
Have great day!

**Comment by premnirmal** [comment]
@Grkrz if you would like the version without analytics you can download it from F-droid. Link in the readme
