### ISSUE TITLE
Screens show information from multiple tabs at once

### ISSUE THREAD

**Issue by jimbudarz** [premnirmal/StockTicker#296]
**Describe the bug**
When switching tabs in the app, the previous tab's content is still visible underneath the new tab's content.

**To Reproduce**
Unfortunately the issue is intermittent and I cannot reliably reproduce it. Closing the app entirely and restarting it resolves the issue temporarily. 

**Expected behavior**
Each tab only shows information pertaining to that tab. 

**Screenshots**
![Screenshot_20220819-070321_Stocks Widget](https://user-images.githubusercontent.com/692898/185638281-2b755d93-6790-4870-93b6-7d69934863e5.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Tab S7
 - OS: Android 12
 - App Version 3.9.800

**Additional context**
None

**Comment by premnirmal** [comment]
This may be fixed on the newest version, can you please update and confirm the bug exists?

Thanks

**Comment by jimbudarz** [comment]
I believe I have the latest version available in F-Droid.

**Comment by premnirmal** [comment]
That's because the play store signs the build with a different key. If you want the one from the play store, you need to uninstall the f-droid version
