### ISSUE TITLE
enhancement: Use tags to mark releases.

### ISSUE THREAD

**Issue by krt16s** [premnirmal/StockTicker#3]
It would be great if you could use git tags to mark new releases, e.g. use `git tag $VERSION` and `git push --tags` on commits that change the version/are considered a release. This would ease up auto-updates of your app in the f-droid.org app repo.

**Comment by premnirmal** [comment]
Thanks Boris.
Using tags now, the current head is tagged at 4.30.00, I'll make sure to add tags to future versions.

Is there a simple way to tag older versions on my previous commits?

**Comment by krt16s** [comment]
Mh, if I read the manpage correctly, `git tag TAGNAME COMMITID` should work. For FDroid old releases don't matter, we don't change already deployed builds. I also set your app to auto-update (once a day).
