### ISSUE TITLE
Only show % change

### ISSUE THREAD

**Issue by olundberg** [premnirmal/StockTicker#301]
On my old phone using this app I could choose between permantly showing % change only.

I bought a new phone now, and the newer version of this widget is constantly (with a few seconds) changing between absolut change and % change? 

Is there a way to only have % change?

**Comment by premnirmal** [comment]
@olundberg yes - go into the app then click widget settings then change 'widget type' to 'fixed'.

Then on the widget tap on the change to toggle between change and % change
