### ISSUE TITLE
app crashes at start up

### ISSUE THREAD

**Issue by Kreuger** [premnirmal/StockTicker#302]
Hey I can no longer open the app to modify my holdings. The app just crashes immediately. I got a [log](https://bin.snopyta.org/?743bce49f122be48#EH1YS1Pea4Ywphps8wUPYNwGszmsLG5yW78D2LtBqfGL) . Using version 3.9.802 on Android 11.

**Comment by premnirmal** [comment]
Hello, does the issue persist with the latest version ie **3.9.809**?

**Comment by Kreuger** [comment]
No it's workine fine now, thanks.
