### ISSUE TITLE
Outdated version on f-droid

### ISSUE THREAD

**Issue by tuch96** [premnirmal/StockTicker#303]
The current version on github does not match with the version on f-droid. A technical problem?

**Comment by premnirmal** [comment]
Yes a problem with F-droid I imagine, the all is building fine so not sure what could be going wrong

**Comment by licaon-kter** [comment]
F-Droid can't find any new version from this: https://github.com/premnirmal/StockTicker/blob/master/app/build.gradle#L61-L76

Any way to have versionCode/Name as static? Else we/you/users need to open a MergeRequest that adds each new version.

**Comment by premnirmal** [comment]
Yes, there has always been a static version exclusively for f-droid: https://github.com/premnirmal/StockTicker/blob/master/app/version.properties

**Comment by licaon-kter** [comment]
Indeed, silly me, missed it in the recipe:
`UpdateCheckData: app/version.properties|versionCode=(.*)|.|versionName=(.*)`

**Comment by licaon-kter** [comment]
That being said... still not an F-Droid error ;)

**Comment by premnirmal** [comment]
Thanks, merged your PR. Is there anything that needs to be done to trigger a build from F-droid?

**Comment by licaon-kter** [comment]
No, next checkupdate (in less than 24h will pick it up)

**Comment by premnirmal** [comment]
Still no update in f-droid?

**Comment by licaon-kter** [comment]
A cycle is ongoing already: https://monitor.f-droid.org/builds/running
Update was auto picked up: https://gitlab.com/fdroid/fdroiddata/-/commit/80c3e1a7617fde582e8392c6ea720ff79735dac8
I've updated the recipe for the new buildserver: https://gitlab.com/fdroid/fdroiddata/-/commit/0faae051e7d85b30a3029fd1fb160fd21cef6049
Next cycle will build it.

FYI, https://gitlab.com/fdroid/wiki/-/wikis/FAQ#how-long-does-it-take-for-my-app-to-show-up-on-website-and-client

**Comment by premnirmal** [comment]
still no build on f-droid

**Comment by licaon-kter** [comment]
The cycle started on 2022-10-19 06:28:08UTC... see monitor link... the app was already built
