### ISSUE TITLE
QMNIX

### ISSUE THREAD

**Issue by Spqr753** [premnirmal/StockTicker#31]
This  ticker isn't displaying can you pls add to the server

**Comment by premnirmal** [comment]
Updated, thanks for the feedback.

**Comment by Spqr753** [comment]
Premium - Could you create a separator that you could add to the security list?  I'd love to group my stock, bonds, mutual funds, and separate them with a dash or something, like this:
Stock1Stock1---Bond1Bond1---Fund1Fund2
I don't know if that's tough to do.




-------- Original message --------From: Prem Nirmal <notifications@github.com> Date: 02/06/2017  16:33  (GMT+00:00) To: premnirmal/StockTicker <StockTicker@noreply.github.com> Cc: Spqr753 <Spqr753@yahoo.com>, Author <author@noreply.github.com> Subject: Re: [premnirmal/StockTicker] QMNIX (#31) 
Updated, thanks for the feedback.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/premnirmal/StockTicker","title":"premnirmal/StockTicker","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/premnirmal/StockTicker"}},"updates":{"snippets":[{"icon":"PERSON","message":"@premnirmal in #31: Updated, thanks for the feedback."}],"action":{"name":"View Issue","url":"https://github.com/premnirmal/StockTicker/issues/31#issuecomment-305822704"}}}

**Comment by premnirmal** [comment]
Hi @Spqr753 , do you mean a separator in the app or in the widget?

**Comment by Spqr753** [comment]
In the widget. I think it would be nice to organize tickets into groups. I tried to have multiple widgets with different tickets but I don't think that works. 



-------- Original message --------From: Prem Nirmal <notifications@github.com> Date: 09/06/2017  14:18  (GMT+00:00) To: premnirmal/StockTicker <StockTicker@noreply.github.com> Cc: Spqr753 <Spqr753@yahoo.com>, Mention <mention@noreply.github.com> Subject: Re: [premnirmal/StockTicker] QMNIX (#31) 
Hi @Spqr753 , do you mean a separator in the app or in the widget?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/premnirmal/StockTicker","title":"premnirmal/StockTicker","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/premnirmal/StockTicker"}},"updates":{"snippets":[{"icon":"PERSON","message":"@premnirmal in #31: Hi @Spqr753 , do you mean a separator in the app or in the widget?"}],"action":{"name":"View Issue","url":"https://github.com/premnirmal/StockTicker/issues/31#issuecomment-307386114"}}}

**Comment by premnirmal** [comment]
Got it. I think this will be solved with multiple widgets which is in progress, will update you once it's out. Thanks.

**Comment by Spqr753** [comment]
Cool thx, what's the ETA for that, do you think?



-------- Original message --------From: Prem Nirmal <notifications@github.com> Date: 09/06/2017  17:56  (GMT+00:00) To: premnirmal/StockTicker <StockTicker@noreply.github.com> Cc: Spqr753 <Spqr753@yahoo.com>, Mention <mention@noreply.github.com> Subject: Re: [premnirmal/StockTicker] QMNIX (#31) 
Got it. I think this will be solved with multiple widgets which is in progress, will update you once it's out. Thanks.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/premnirmal/StockTicker","title":"premnirmal/StockTicker","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/premnirmal/StockTicker"}},"updates":{"snippets":[{"icon":"PERSON","message":"@premnirmal in #31: Got it. I think this will be solved with multiple widgets which is in progress, will update you once it's out. Thanks."}],"action":{"name":"View Issue","url":"https://github.com/premnirmal/StockTicker/issues/31#issuecomment-307442987"}}}

**Comment by premnirmal** [comment]
Probably about 2 weeks, since I only do this in my spare time.

**Comment by Spqr753** [comment]
Ok thanks.  Again, great widget.  



-------- Original message --------From: Prem Nirmal <notifications@github.com> Date: 09/06/2017  20:01  (GMT+00:00) To: premnirmal/StockTicker <StockTicker@noreply.github.com> Cc: Spqr753 <Spqr753@yahoo.com>, Mention <mention@noreply.github.com> Subject: Re: [premnirmal/StockTicker] QMNIX (#31) 
Probably about 2 weeks, since I only do this in my spare time.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/premnirmal/StockTicker","title":"premnirmal/StockTicker","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/premnirmal/StockTicker"}},"updates":{"snippets":[{"icon":"PERSON","message":"@premnirmal in #31: Probably about 2 weeks, since I only do this in my spare time."}],"action":{"name":"View Issue","url":"https://github.com/premnirmal/StockTicker/issues/31#issuecomment-307473066"}}}

**Comment by Spqr753** [comment]
It'd be cool if you could label each iteration of the widget, if you are able to have multiple ones. 



-------- Original message --------From: Prem Nirmal <notifications@github.com> Date: 09/06/2017  17:56  (GMT+00:00) To: premnirmal/StockTicker <StockTicker@noreply.github.com> Cc: Spqr753 <Spqr753@yahoo.com>, Mention <mention@noreply.github.com> Subject: Re: [premnirmal/StockTicker] QMNIX (#31) 
Got it. I think this will be solved with multiple widgets which is in progress, will update you once it's out. Thanks.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/premnirmal/StockTicker","title":"premnirmal/StockTicker","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/premnirmal/StockTicker"}},"updates":{"snippets":[{"icon":"PERSON","message":"@premnirmal in #31: Got it. I think this will be solved with multiple widgets which is in progress, will update you once it's out. Thanks."}],"action":{"name":"View Issue","url":"https://github.com/premnirmal/StockTicker/issues/31#issuecomment-307442987"}}}

**Comment by Spqr753** [comment]
Hi. The latest update lost almost all my tickets, is it just me?



-------- Original message --------From: Prem Nirmal <notifications@github.com> Date: 02/06/2017  11:33  (GMT-05:00) To: premnirmal/StockTicker <StockTicker@noreply.github.com> Cc: Spqr753 <Spqr753@yahoo.com>, Author <author@noreply.github.com> Subject: Re: [premnirmal/StockTicker] QMNIX (#31) 
Updated, thanks for the feedback.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/premnirmal/StockTicker","title":"premnirmal/StockTicker","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/premnirmal/StockTicker"}},"updates":{"snippets":[{"icon":"PERSON","message":"@premnirmal in #31: Updated, thanks for the feedback."}],"action":{"name":"View Issue","url":"https://github.com/premnirmal/StockTicker/issues/31#issuecomment-305822704"}}}

**Comment by Spqr753** [comment]
Prem - I am having a lot of trouble with the app. It's not showing my tickets as of the update. When I add them back, a pop-up says they are already in the portfolio. And when I add a new one it appears in all the widgets, rather than the one I put it in. Are others having the same issues?



-------- Original message --------From: Prem Nirmal <notifications@github.com> Date: 02/06/2017  11:33  (GMT-05:00) To: premnirmal/StockTicker <StockTicker@noreply.github.com> Cc: Spqr753 <Spqr753@yahoo.com>, Author <author@noreply.github.com> Subject: Re: [premnirmal/StockTicker] QMNIX (#31) 
Updated, thanks for the feedback.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/premnirmal/StockTicker","title":"premnirmal/StockTicker","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/premnirmal/StockTicker"}},"updates":{"snippets":[{"icon":"PERSON","message":"@premnirmal in #31: Updated, thanks for the feedback."}],"action":{"name":"View Issue","url":"https://github.com/premnirmal/StockTicker/issues/31#issuecomment-305822704"}}}

**Comment by tuliom** [comment]
@Spqr753 same issue here.

**Comment by Spqr753** [comment]
Hi, can you please add a ticker for Ethereum Classic?



_______________
Spqr753
________________________________
