### ISSUE TITLE
Cannot import quotes from json

### ISSUE THREAD

**Issue by formerunicornbroker** [premnirmal/StockTicker#311]
Nothing happens when tapping on import or export quotes.
Settings> import quotes 
Should allow browsing to previously exported json file

Redmi k20 pro (mi 9t [raphael])
LineageOS android 13

**Comment by GollyJer** [comment]
Came to report the same issue.
Unable to transfer to new phone. The share button also does nothing.

**Comment by premnirmal** [comment]
Upon clicking share, does it prompt you to pick a file / create a file using the file picker?

**Comment by charkins** [comment]
I have the same issue as well, does not prompt. I assume this is related to the scoped storage stuff added in Android 11. It works correctly on my Pixel 4 on Android 13 (build TP1A.221005.002), but not on Pixel 7 running slightly newer Android 13 (build TD1A.221105.001).

I think this is the relevant logcat lines when trying to click the `Import quotes` (or `Share Portfolio` or `Export quotes`) options:
```
11-28 21:47:25.628  3473  3473 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1876 onStartInput(EditorInfo{inputType=0x0(NULL) imeOptions=0x0 privateImeOptions=null actionName=UNSPECIFIED actionLabel=null actionId=0 initialSelStart=-1 initialSelEnd=-1 initialCapsMode=0x0 hintText=null label=null packageName=com.github.premnirmal.tickerwidget fieldId=2131362251 fieldName=null extras=null}, false)
11-28 21:47:25.628  3473  3473 I GoogleInputMethodService: GoogleInputMethodService.shouldHideHeaderOnInitialState():3985 ShouldHideHeaderOnInitialState = false
11-28 21:47:25.629  3473  3473 I GoogleInputMethodService: GoogleInputMethodService.updateDeviceLockedStatus():2085 repeatCheckTimes = 2, unlocked = true
11-28 21:47:25.645  1674  4056 D CoreBackPreview: Window{21ba443 u0 com.google.android.permissioncontroller/com.android.permissioncontroller.permission.ui.GrantPermissionsActivity}: Setting back callback null
11-28 21:47:25.645  1674  4394 W InputManager-JNI: Input channel object '21ba443 com.google.android.permissioncontroller/com.android.permissioncontroller.permission.ui.GrantPermissionsActivity (client)' was disposed without first being removed with the input manager!
```

**Comment by formerunicornbroker** [comment]
> Upon clicking share, does it prompt you to pick a file / create a file using the file picker?

No prompt at all from import, export or share.

logcat:

InputManager-JNI: Input channel object '79d10b Splash Screen com.github.premnirmal.tickerwidget (client)' was disposed without first being removed with the input manager!

**Comment by premnirmal** [comment]
Thank you for the fix @charkins
