### ISSUE TITLE
Portfolio Tab

### ISSUE THREAD

**Issue by seniorm0ment** [premnirmal/StockTicker#317]
A specific tab for portfolios would be very nice.

**Comment by g6094199** [comment]
it would be nice to "cluser" stocks.

e.g. is have several traders with a amount of stock. 

with a "clustering"  option i could determine which stock "cluster" i at which trading account.

this could also be achieved with several portfolios.

**Comment by g6094199** [comment]
cab be closed, cause its covered by: https://github.com/premnirmal/StockTicker/issues/159
