### ISSUE TITLE
Material you themed app icon

### ISSUE THREAD

**Issue by riScoRpIng** [premnirmal/StockTicker#327]
It would be nice to see monochromatic themed app icon which was released on Android 13 (or 12?). Thank you. 

See easy implementation: https://proandroiddev.com/android-13-implementing-themed-icons-into-your-app-e7002f2c4e04

**Comment by premnirmal** [comment]
Updated in https://github.com/premnirmal/StockTicker/commit/12765b974adf9669042664d82d1ec68f7d8028d0, v3.9.819
