### ISSUE TITLE
Refresh fails to fetch

### ISSUE THREAD

**Issue by jpl-mac** [premnirmal/StockTicker#328]
**Describe the bug**
Refreshing the stock quotes stopped working around midday on April 19th 2023.

**To Reproduce**
1. From inside the app
2. drag down to cause a refresh
3. Toast appears at bottom with "Refresh failed" or pop up with "Failed to fetch"
4. Similar issue with the refresh round arrow in widget.

**Expected behavior**
Stocks values are updated as usual

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - OS: CalyxOS (Android 13)
 - App Version [e.g. 3.9.819]

**Additional context**
Likely caused by the remote server having issue or API having change.

**Comment by jpl-mac** [comment]
It's working again 24h later without changes to the app.  Closing the issue

**Comment by ZisBoom** [comment]
> It's working again 24h later without changes to the app. Closing the issue

Hasn't started working again for me in my other issue.

**Comment by jpl-mac** [comment]
@ZisBoom that was 2 weeks ago.  It's also not working anymore for me since the time off your issue.
