### ISSUE TITLE
Too much data usage

### ISSUE THREAD

**Issue by vhda** [premnirmal/StockTicker#337]
**Describe the bug**
This app used my complete monthly allowance of data usage of ~2Gb in just 2 days. I noticed this yesterday when it reached 500 Mb and disabled background data usage for the app, but unfortunately that wasn't enough and today it used the remainder within 1h.
I'm on 3.9.822. Not sure if this is a new option but today, after the fact, I've found a setting to only update every hour instead of every minute.

**To Reproduce**
Disconnect from wifi.

**Expected behavior**
App should not use so much data.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung A52S 5G
 - OS: Android 13
 - App Version: 3.9.822

**Additional context**

**Comment by ovz93br43v7** [comment]
Same problem here 5,69GB background data used:
- Device: Pixel 6
- OS: Android 13
- App Version: 3.9.822

**Comment by premnirmal** [comment]
Can you both update to the latest version?

Regardless, I am unsure why the data usage is so high. The only change is we're invoking `https://finance.yahoo.com/` to fetch cookies, and that has a large response.

On my phone it is showing 40MB in the past month

**Comment by vhda** [comment]
In 821 the minimum update time was 15 min, which was decreased to 1 min in 822 and the new minimum became the default setting automatically. This app was also the top power consumer, which means it was constantly waking up, although I'm not sure this was related with the 1 min update.
@ovz93br43v7 could you confirm the power consumption symptom on your end?
@premnirmal can't test much since I now don't have anymore data available in my plan for the coming ~30 days...

**Comment by premnirmal** [comment]
@vhda 
> update time was 15 min, which was decreased to 1 min in 822 and the new minimum became the default setting automatically

That is not true, there is no 'new minimum'. It has always been 15min as default, and you change it in settings

**Comment by vhda** [comment]
That's odd. Updated back to 822 and I confirm there is no 1 min setting available. Could swear I saw it there yesterday! Sorry for sharing this incorrect information.
BTW, 822 is still the latest version available in F-Droid, so I can't update further.

**Comment by premnirmal** [comment]
I'd recommend using the play store because updates are quicker. F-droid is not very good with updates, it is very slow on picking up changes.

The latest version today is 825 so f-droid is already 3 versions behind

**Comment by ovz93br43v7** [comment]
> @ovz93br43v7 could you confirm the power consumption symptom on your end? 
In my case 43% power consumption caused by this app.

> @premnirmal can't test much since I now don't have anymore data available in my plan for the coming ~30 days...
Same problem here data plan is empty.

> Can you both update to the latest version?
I have to wait until F-Droid shows a new release.

**Comment by premnirmal** [comment]
It's a shame you have to wait for f-droid. You wouldn't have this problem with Google play, or if you just grab the APK from the releases section of the repo

**Comment by vhda** [comment]
823 is already available and I don't see the CPU usage at least. Now, until mid June I can't be sure because I don't have a data plan until then. The release notes of 823do mention something about "Updates to scheduling and reduce list of updates", do maybe that was the fix?

**Comment by maxen0815** [comment]
> Which version are you on?

Added in my original post

**Comment by panro** [comment]
I also had this issue, and noticed the widget was flickering **a lot** in the same day(s) it was happening.

It might be related to https://github.com/premnirmal/StockTicker/issues/333 which also mentions a flicker. In fact, I have a similiar situation as that issue's reporter: I also monitor multiple global markets, so I set the app to fetch data over a wide range of hours (from 9:15 to 23:15 on UTC+3).

- Device: Asus Zenfone 8
- OS: Android 13
- App Version: not sure - was auto-updated since the issue happened (haven't used the app since)

**Comment by premnirmal** [comment]
You could update to the latest version instead of staying on old versions?
