### ISSUE TITLE
getcrumb http get need valid user agent

### ISSUE THREAD

**Issue by muziofg** [premnirmal/StockTicker#340]
since yesterday (22:00 UTC+2, circa) the endpoint https://query2.finance.yahoo.com/v1/test/getcrumb accept only request from client with an user agent that pretend to be a browser 

I have also a request: can you reconsider your last commit about minSDK version ? I have an Android 8 and I would receive this patch 

1. Trying to fetch some data (best if are new stocks)
2. App enter in a infinite loading loop

 - Device: LG Q7
 - OS: Android 8
 - App Version 3.9.825

**Comment by premnirmal** [comment]
> since yesterday (22:00 UTC+2, circa) the endpoint https://query2.finance.yahoo.com/v1/test/getcrumb accept only request from client with an user agent that pretend to be a browser

Thanks, do you have any sources on this?

**Comment by premnirmal** [comment]
What is the user agent you are using?

**Comment by premnirmal** [comment]
Fixed in https://github.com/premnirmal/StockTicker/commit/25ea96551d5d2ceebfad062255afddbabc1bf863

**Comment by muziofg** [comment]
well done
Now you can consider to set minSdkVersion to 27 (Android 8.1) instead of 28 ? 
I'm still using a device with this version

**Comment by muziofg** [comment]
> well done Now you can consider to set minSdkVersion to 27 (Android 8.1) instead of 28 ? I'm still using a device with this version

Thanks for the last update
