### ISSUE TITLE
App drained 20% of battery

### ISSUE THREAD

**Issue by anton-isidore** [premnirmal/StockTicker#341]
**Describe the bug**
Yesterday, the app drained 20% of my bettery.

I have one widget with two currency pairs.

**To Reproduce**
Well, this is probably hard. 

- I have update interval 15minutes (I already changed to to 1h)

**Expected behavior**
Not draining the battery.

**Screenshots**
(I have charged my phone, thus lost the Battery Usage overview with this situation.)

**Smartphone (please complete the following information):**
 - Device: OnePlus 7
 - OS: LineageOS
 - App Version; 3.9.826

**Comment by premnirmal** [comment]
This was a bug in the app, update to version 3.9.827 and the battery drain is fixed

**Comment by premnirmal** [comment]
https://github.com/premnirmal/StockTicker/commit/b4b3095735b6c841b32d368d1263956b81c8a6a2
