### ISSUE TITLE
Quote feeds stopped working

### ISSUE THREAD

**Issue by akasaka99** [premnirmal/StockTicker#342]
**Describe the bug**
Updates quotes stopped since Thursday 20 July.

**To Reproduce**
Rebooted and tried to refresh but to no avail.
Expemple of quotes: SPX, Nasdaq, Currencies, Commodiites and bitcoin: total = 15 quotes

**Expected behavior**
Update interval: 5mins

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung S22
 - OS: Android 12
 - App Version  3.9.825

**Additional context**

**Comment by akasaka99** [comment]
Sorry I dont understans why the issue was closed? I dont see any note on the main page.
Is the project dead?

**Comment by premnirmal** [comment]
Update the app

**Comment by akasaka99** [comment]
ok tks

**Comment by premnirmal** [comment]
https://github.com/premnirmal/StockTicker/commit/b4b3095735b6c841b32d368d1263956b81c8a6a2
