### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by Spqr753** [premnirmal/StockTicker#345]
The most recent update increased the font size significantly, and I would like to at very least decrease it back to it's original size.  And if possible, I would like it even smaller that it was prior to the update.  Is this possible, maybe by allowing selection of various font sizes?

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by premnirmal** [comment]
There is a font size setting in the app
