### ISSUE TITLE
Displaying stocks in a list

### ISSUE THREAD

**Issue by jorgeYa** [premnirmal/StockTicker#346]
I cannot display the portfolio in a list one stock per line as shown . I can only set the text size, but I have not option to change the widget mode to display a list. 
It's a bug or am I missing something?

**Comment by premnirmal** [comment]
![Screenshot_20230813-100657.png](https://github.com/premnirmal/StockTicker/assets/1255689/b8f92fe5-cc60-4405-b6f0-7b63f390f139)

It's there, unless you're looking at a different app? Maybe you're confusing the Chrome browser app with the stocks widget app?

**Comment by jorgeYa** [comment]
This are my options



Prem Nirmal ***@***.***> schrieb am So., 13. Aug. 2023, 11:08:
