### ISSUE TITLE
Battery drain in the latest versions

### ISSUE THREAD

**Issue by saddy001** [premnirmal/StockTicker#348]
Since the latest version(s), 3.9.829 or .828 stocks widget is the top battery consuming app on my phone. My battery is empty pretty quickly now. I analyzed with the stock battery app usage overview of android and it is also observable in SystemPanel. 
SW used 33% of my battery although I usually only open the app for a few seconds 2-3 times a day. However, I also use the widget.

- Android battery usage is set to "unrestricted".
- In the app settings refresh interval is set to 10:00 to 19:00 from monday to friday. I have 10 stocks in the list. The SW notification (not the android one) is disabled in the app settings.
- Update interval is set to 1 hour (but that may not be honored, see #287)
- Device: pioneer
- OS: lineageOS (Android 12)

I noticed that you added some nice animations of stock tickers changing when opening the app. Are you sure these animations are disabled when the app is closed?

**Comment by jayb-g** [comment]
Firsr of all. Great app. Love the functionalities. The only issue I faced was battery usage. So came here and found it to be reported as fixed.

Two battery drain issues are closed. But unfortunately the issue persists.

Both of the reported issues(#341 and #348)come from lineageOS. Meaning they probably don't have Google Play services installed. Just assuming.

@premnirmal as per the [privacy policy](https://github.com/premnirmal/StockTicker/blob/master/PRIVACY_POLICY.md) of the app, it seems that the app depends on GPS for at least some of the functionality. Probably for notifications(if alerts are set)?

I also have just 1 widget, and no GPS, using latest version of the app(v3.9.834) with all the default settings. I just added alerts(for high and low values) for each of the 3 testing stocks I added to the widget. It consumes more than 10% battery at least over just a few hours, could have been more if I had kept it running in background for some more time. Ideally it should consume <1% battery given the functionality of the app serving purely as a widget. I tested similar [crypto widget](https://f-droid.org/packages/com.brentpanther.bitcoinwidget) app(with the same default update interval of 15 mins) and it does indeed use <1% battery, although it doesn't have the price alert functionality. Maybe you can review its code and implement the update mechanism similarly?
