### ISSUE TITLE
Better widget UI

### ISSUE THREAD

**Issue by inson1** [premnirmal/StockTicker#353]
**Is your feature request related to a problem? Please describe.**
Your widget is just ugly imo. I mean it in constructive way.
I like webull widget UI for example.

**Describe the solution you'd like**
Fetch/Update should be on bottom
Widget name should be on fetch place
Stock price should be on right part of the widget
There should be separation between stocks
There should be more info about the stocks - name of the company etc., name of the exchange - this is only one that isnt important

**Describe alternatives you've considered**
I think the widget needs redesign. - More informations can be optional. 3) and 4) is no brainer imho. 1) and 2) would also helped imho. But if someone doesnt like there is always option to make it optional.

**Additional context**
![image](https://github.com/premnirmal/StockTicker/assets/75314629/ba260aba-e50d-459f-b128-7dab68819938)
![image](https://github.com/premnirmal/StockTicker/assets/75314629/464a7207-528d-4c16-b180-ddd0d7b9dc9c)

**Comment by inson1** [comment]
@premnirmal Why do you close issues without explanation?

**Comment by premnirmal** [comment]
@inson1 your issue didn't follow the issue template

**Comment by inson1** [comment]
@premnirmal Now it does. May you reopen the issue?

PS Please add at least label or few words before you close any issue.
