### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by Poussinou** [premnirmal/StockTicker#36]
Hi @premnirmal 

I found [this app](https://play.google.com/store/apps/details?id=com.ingic.smartstock) on the Google Play Store. This guy just took your source code and put it on the Store, without warning this is free software...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove the false app from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under MIT license and this guy is violating it;
* He is falsely claiming he made the app.

**Comment by premnirmal** [comment]
Hi @Poussinou thanks for letting me know. It's a shame that this guy didn't give any acknowledgements to the original source. I appreciate you looking out for this.
