### ISSUE TITLE
Import fauliure after update. 

### ISSUE THREAD

**Issue by Grkrz** [premnirmal/StockTicker#366]
**Describe the bug**
- App Version [e.g. 3.9.123] **Please make sure you are not on an outdated app version before you file an issue, otherwise your issue will be closed. You can check the latest version in the releases part of the repo**.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by premnirmal** [comment]
Closing this bug because you did not include any information
