### ISSUE TITLE
Import fauliure after update.

### ISSUE THREAD

**Issue by Grkrz** [premnirmal/StockTicker#367]
Update from 3.9.830 to [3.9.833] caused that i cannot import my stocks from previous version. 

I had unistall the app version 3.9.830 in order to update to 3.9.833 as it is a fail when updating via Obtainium. 

After  unisalling the 3.9.830 and installing the newest app I cannot import the stocks . 

When I went back to the 3.9.830 version it works. I can import the stocks from .json file.

**Comment by premnirmal** [comment]
Fixed in https://github.com/premnirmal/StockTicker/commit/d6e920ce8bfd231730d220e93ed46031bd267f35, 3.9.834
