### ISSUE TITLE
The current version on F-droid (V 3.9.832) does not update the stocks any more. 

### ISSUE THREAD

**Issue by 01stakanov** [premnirmal/StockTicker#368]
Since the update to this version - 3.9.832 from f-droid  (from the previous one) the app behaves as following: 
- no stock courses are updated. 
- if one insists several times manually to update the course notations, the app claims "update failed" (on my system aggiornatmento fallito as it is in Italian local). 
Otherwise the app works, last update is 10.14 Saturday. The app shows "next update" in the correct defined timeframe, but appears not to be able to perform it. I am using a VPN wireguard connection. I also tried the app without VPN, but it makes no difference. Same behaviour/error. 

curiously the app is not available on f-froid in my shop any more (although I find it on the web). This could be due to the fact that it is already installed.

**Comment by 01stakanov** [comment]
Thank you for your time and patience.

**Comment by licaon-kter** [comment]
The issue is @premnirmal that F-Droid does not see any new version: https://github.com/premnirmal/StockTicker/blob/3.9.834/app/version.properties nor can I :smile:

**Comment by premnirmal** [comment]
Thanks, vcode is updated. In the future I will remove this file, because the version code and version name is inferred from the tag. If F-droid is not smart enough to infer that then tough :)

**Comment by licaon-kter** [comment]
An odd way to say it, those are used for a purpose, right?

**Comment by premnirmal** [comment]
It is unnecessary, because the version code and name is part of the git tag

**Comment by licaon-kter** [comment]
So versionCode is `3` and versionName is `9.832` ? :stuck_out_tongue: 

We will need to disable autoupdates if we can't get get the version code and name in a static way _(since https://github.com/premnirmal/StockTicker/blob/3.9.834/app/build.gradle#L34-L41 and https://github.com/premnirmal/StockTicker/blob/3.9.834/app/build.gradle#L65-L69 are unparsable as F-Droid checkupdate process does not execute code)_

**Comment by premnirmal** [comment]
Code and name is extracted from the git tag here: https://github.com/premnirmal/StockTicker/blob/master/app/build.gradle#L69. F-droid can do this, because the `version.properties` file will no longer be supported

**Comment by licaon-kter** [comment]
As explained, I'll disable autoupdates if not possible to have static versions :( Hopefully users can ping us or open MRs directly when new updates are released

**Comment by r-zack** [comment]
Same here. v. 3.9.832, updated via F-Droid. The app does not update stock prices anymore since the last update. Please solve this bug. Thank you very much!
