### ISSUE TITLE
Delete a widget from app

### ISSUE THREAD

**Issue by webmihir** [premnirmal/StockTicker#37]
My StockTicker shows two widgets when I open the app. However only one is used. I don't see any way to delete a widget.

**Comment by premnirmal** [comment]
Hi @webmihir . You cannot delete a widget from the app, you can only delete widgets from your launcher. If you have more than one launcher installed, the second widget may have been added in a  different launcher. You can either open that launcher and remove the widget, or delete that launcher, and the widget will be removed.

**Comment by webmihir** [comment]
Thanks @premnirmal 
For some reason I could not find the unused widget on any of my launchers (I only have one launcher installed - the default one that came with Google Pixel). I had to un-install and re-install the app; and now the unused widget is gone.
