### ISSUE TITLE
Failed to fetch ^DJI

### ISSUE THREAD

**Issue by ShakataGaNai** [premnirmal/StockTicker#41]
Loaded up the widget for the first time and wanted to pull the generic market information, tried to add Dow Jones and got "Failed to fetch ^DJI". All the others I tried worked, except that one. Also once you add the corrupted ticker - all others in the list after it will also fail to fetch data.

**Comment by premnirmal** [comment]
Dow Jones should work now. However, you will need to add `.DJI`, and not `^DJI`

**Comment by alexeip0** [comment]
I guess this is an issue for any stock which ticker starts with caret (^). I cannot add NASDAQ (^IXIC) or any T notes like ^TNX. And I cannot use the above trick of replacing '^' with '.'

**Comment by alexeip0** [comment]
Couldn't add FFFEX too. Also once you attempt to add "unfetchable" ticker, even if you remove it afterwards, cannot add anymore normal tickers.

**Comment by tomamplius** [comment]
Samedi for me on version 2.3.22.

I can't fetch ILD.PA and GLE.PA and other

Second point : GLE.PA Real name have an encode issue.
Société générale -> sociã©tã© gã©nã©ral
