### ISSUE TITLE
AlarmManager.set is not scheduling the alarms at the exact time after API 19

### ISSUE THREAD

**Issue by frankFic** [premnirmal/StockTicker#42]
Hi, I found `AlarmManager.set()` is used in [AlarmScheduler](https://github.com/premnirmal/StockTicker/blob/5571c8111b26b38113af5a2be4f3bd0176ab3aa8/app/src/main/kotlin/com/github/premnirmal/ticker/model/AlarmScheduler.kt#L111) to schedule alarms. From API 19, the alarms scheduled by this API will not be exact: the alarm will not be delivered before this time, but may be deferred and delivered some time later. ([doc](https://developer.android.com/reference/android/app/AlarmManager.html#set(int,%20long,%20android.app.PendingIntent))) From API 19, API `setExact` will schedule the alarms at the exact time. I am not pretty sure wether the time need to be exact so I leave this information for your reference.

**Comment by premnirmal** [comment]
Thanks for reporting the issue. Would you like to file a PR?

**Comment by frankFic** [comment]
Yes. I will make one later.
