### ISSUE TITLE
Tickers not appearing. 

### ISSUE THREAD

**Issue by Spqr753** [premnirmal/StockTicker#46]
I am having a lot of trouble with the app. It's not showing my tickers as of the update. When I add them back, a pop-up says they are already in the portfolio. And when I add a new one it appears in all the widgets, rather than the one I put it in. Are others having the same issues?

**Comment by pdftk** [comment]
Same issue here. But only for the local german stock exchange ticker. Example: AMEM.DE is not showing, while OHI is working.
