### ISSUE TITLE
Unauthorised - Refresh failed

### ISSUE THREAD

**Issue by prohealthbox** [premnirmal/StockTicker#50]
After build this project in Android Studio and importing apk to my phone,  I am getting this error message

Unauthorised.

Refresh Failed.

Kindly help.

**Comment by prohealthbox** [comment]
can anyone, please help me 
@howeyc @premnirmal @frankFic

**Comment by premnirmal** [comment]
It is because your app is not authorized to use the API. The API is protected by auth.

**Comment by prohealthbox** [comment]
@premnirmal can you please let me know how to get authorization..?

**Comment by elfelround** [comment]
why is this even closed
