### ISSUE TITLE
Refresh fails at times

### ISSUE THREAD

**Issue by SubSi** [premnirmal/StockTicker#53]
![screenshot_2018-03-19-18-39-55](https://user-images.githubusercontent.com/22346451/37650588-a79c5110-2c35-11e8-8ede-338f558fd5ed.png)

**Comment by SubSi** [comment]
Seems to work fine again

**Comment by SubSi** [comment]
Sorry, it keeps having trouble refreshing.

**Comment by webmihir** [comment]
+1, getting the same error.

**Comment by numericOverflow** [comment]
I have the same issue.

@webmihir, @SubSi - do you both have the Dow Jones Industrial Average listed in your portfolio?

I noticed that the exceedingly long error message suggests the app gets multiple results when querying "DJI" from Google finance - one for the DOW, and another for DJI (the drone mfg company).

I'm guessing once it encounters that uncaught exception, all updates fail.

**Comment by webmihir** [comment]
I don't have Dow Jones.
I have:

^GSPC
ES=F
^IXIC
BTCUSD=X
BND
ETHUSD=X
VNQ
MSFT
VTI
AMZN
VXF
AAPL
VBR
GOOGL
IJS
NFLX
VXUS
FB
VWO
SNAP
VDE
CRM
IAU
TSLA

**Comment by premnirmal** [comment]
`^DJI` and `.DJI` were causing the issue. They should work now
