### ISSUE TITLE
problem with spanish stocks

### ISSUE THREAD

**Issue by legionarios** [premnirmal/StockTicker#6]
Hi, trying to look for spanish stocks (OHL.MC and ABE.MC) it does find them but it doesn't show any price or data whatsoever.
any help?
Thanks and congrats, MAGNIFICENT app!!!

**Comment by premnirmal** [comment]
Looks like yahoo finance's YQL api doesn't show those stocks. Have a look here: https://developer.yahoo.com/yql/console/?q=select%20%2a%20from%20yahoo.finance.quote%20where%20symbol%20in%20%28%22YHOO%22%2C%22AAPL%22%2C%22GOOG%22%2C%22MSFT%22%29&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys#h=select+*+from+yahoo.finance.quote+where+symbol+in+(%22OHL.MC%2C+ABE.MC%22)

**Comment by legionarios** [comment]
thanks for the help!
