### ISSUE TITLE
App version too old error

### ISSUE THREAD

**Issue by jceresini** [premnirmal/StockTicker#65]
When the stock ticker tries to update (as a widget, or when i launch it as an app) i get a popup message that says "App version too old 2.5.15(251) (Android 26; motorola moto g(6) please update." The error message doesn't indicate what to update, but there are no updates available for the StocksWidget in the google play store (and its version seems to match the latest in the releases tab in this project).

It worked up until yesterday afternoon (according to the last successful update reported in the app). I don't see a way to determine if it was auto-updated recently in the play store, but its not in the list of recently updated apps.

Happy to provide more details if needed

**Comment by jceresini** [comment]
![stockswidgeterror](https://user-images.githubusercontent.com/1152102/43415156-d2006fb0-9402-11e8-94d5-13bf0031c33c.png)

**Comment by premnirmal** [comment]
This was a server bug, should be fixed now

**Comment by jceresini** [comment]
Its working now. thanks for the follow up!
