### ISSUE TITLE
Cannot add multiple purchase lots

### ISSUE THREAD

**Issue by dyslexicanaboko** [premnirmal/StockTicker#67]
I can understand if this isn't a feature you would want to include because it makes everything more complicated, but here is the idea:

- You purchase a stock ABC on 01/01/2017 for $1 a share for 1000 shares
- Then you purchase the same stock ABC on 01/01/2018 for $2 a share for 500 shares

Currently I cannot add the stock to my portfolio multiple times, but I also don't have a way to add separate purchase lots for the same stock in my portfolio.

Just an idea.

**Comment by premnirmal** [comment]
Hello, thanks for reporting the issue. Right now there is a pull request open for this https://github.com/premnirmal/StockTicker/pull/64

**Comment by dyslexicanaboko** [comment]
Thank you! That's awesome.
