### ISSUE TITLE
Removing stock from one widget removes it from all widgets

### ISSUE THREAD

**Issue by dyslexicanaboko** [premnirmal/StockTicker#68]
1. Create two widgets - Widget A and Widget B
2. Add three stocks to Widget A - tickers 1, 2, 3
3. Add one stock to Widget B - ticker 1
4. Remove ticker 1 from Widget A
5. You will now see that ticker 1 is now gone from both Widget A and Widget B

Pretty sure that's a bug/oversight, but that's for the author to decide.

**Comment by premnirmal** [comment]
Thanks for reporting, will look in to this. Any help is appreciated!

**Comment by premnirmal** [comment]
Fixed here https://github.com/premnirmal/StockTicker/commit/4c13a05a09b953013e69e64858b89c159bae6728 will be updated in version 2.5.18(254)
