### ISSUE TITLE
Not granular enough

### ISSUE THREAD

**Issue by gappleto97** [premnirmal/StockTicker#72]
FDKVX is traded by the thousandth. You only allow up to a hundredth. Can you please allow us to enter shares more granularly?

**Comment by premnirmal** [comment]
Added up to 4 decimal prices when showing prices. Do you also want the # of shares to be more granular?

**Comment by gappleto97** [comment]
Yes please

**Comment by hbhbhbhbhbhb** [comment]
4dp is brilliant, but has caused % to go crazy, that needs to be rounded to 2dp

**Comment by premnirmal** [comment]
Yes good point, that needs fixing
