### ISSUE TITLE
Berkshire Hathaway class B (BRK-B / BRK.B on NYSE) fails to load

### ISSUE THREAD

**Issue by CDB-Man** [premnirmal/StockTicker#76]
When I add ticker BRK-B (NYSE) to the widget, a failure to load error appears, but the error mentions BRK.B instead of BRK-B. If you click on the ticker the graph appears, but the widget doesn't record the current price

**Comment by CDB-Man** [comment]
Screenshot: https://imgur.com/a/us3HxfE

**Comment by premnirmal** [comment]
Fixed now
