### ISSUE TITLE
bug found in  StockTicker app The application crashes when I click Start Time

### ISSUE THREAD

**Issue by saraji-ali** [premnirmal/StockTicker#79]
# Project Information

* Repository: https://github.com/premnirmal/StockTicker
* Project Name: StockTicker

# Expected behavior

The application should not crash when I click Start Time Option. When I click on, start time should be displayed so that I adjust this start time with custom 

# Actual behavior

The application crashes when I click Start Time

# How to reproduce

1-[Download ](https://play.google.com/store/apps/details?id=com.github.premnirmal.tickerwidget)the app and open it
2- Go to the setting
3- Click here on the Start time option
4- see bug 
* Browser/App version: Current Version 3.0.4
* Operating system: 6.0.1
* Smartphone: Galaxy j7 

# Recording Of The Bug
![20190507_145001](https://user-images.githubusercontent.com/50115498/57293020-49ea7780-7078-11e9-9c4f-17a2d8502954.gif)

# My Github Account
https://github.com/facebook-786

# Logcat

<pre><code>E/AndroidRuntime(11193): FATAL EXCEPTION: main

E/AndroidRuntime(11193): Process: com.github.premnirmal.tickerwidget, PID: 11193

E/AndroidRuntime(11193): android.view.InflateException: Binary XML file line #20: Error inflating class android.widget.TimePicker

E/AndroidRuntime(11193): 	at android.view.LayoutInflater.createView(LayoutInflater.java:633)

E/AndroidRuntime(11193): 	at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(SourceFile:164)

E/AndroidRuntime(11193): 	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)

E/AndroidRuntime(11193): 	at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(SourceFile:148)

E/AndroidRuntime(11193): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)

E/AndroidRuntime(11193): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:482)

E/AndroidRuntime(11193): 	at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(SourceFile:60)

E/AndroidRuntime(11193): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)

E/AndroidRuntime(11193): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:365)

E/AndroidRuntime(11193): 	at android.app.TimePickerDialog.<init>(TimePickerDialog.java:134)

E/AndroidRuntime(11193): 	at android.app.TimePickerDialog.<init>(TimePickerDialog.java:102)

E/AndroidRuntime(11193): 	at com.github.premnirmal.ticker.settings.SettingsFragment.onDisplayPreferenceDialog(SourceFile:113)

E/AndroidRuntime(11193): 	at androidx.preference.PreferenceManager.showDialog(SourceFile:530)

E/AndroidRuntime(11193): 	at androidx.preference.DialogPreference.onClick(SourceFile:258)

E/AndroidRuntime(11193): 	at androidx.preference.Preference.performClick(SourceFile:1167)

E/AndroidRuntime(11193): 	at androidx.preference.Preference.performClick(SourceFile:1152)

E/AndroidRuntime(11193): 	at androidx.preference.Preference$1.onClick(SourceFile:182)

E/AndroidRuntime(11193): 	at android.view.View.performClick(View.java:5076)

E/AndroidRuntime(11193): 	at android.view.View$PerformClick.run(View.java:20279)

E/AndroidRuntime(11193): 	at android.os.Handler.handleCallback(Handler.java:739)

E/AndroidRuntime(11193): 	at android.os.Handler.dispatchMessage(Handler.java:95)

E/AndroidRuntime(11193): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(11193): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime(11193): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(11193): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(11193): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime(11193): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)

E/AndroidRuntime(11193): Caused by: java.lang.reflect.InvocationTargetException

E/AndroidRuntime(11193): 	at java.lang.reflect.Constructor.newInstance(Native Method)

E/AndroidRuntime(11193): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)

E/AndroidRuntime(11193): 	at android.view.LayoutInflater.createView(LayoutInflater.java:607)

E/AndroidRuntime(11193): 	... 26 more

E/AndroidRuntime(11193): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void android.widget.TimePicker$TimePickerDelegate.onRtlPropertiesChanged(int)' on a null object reference

E/AndroidRuntime(11193): 	at android.widget.TimePicker.onRtlPropertiesChanged(TimePicker.java:193)

E/AndroidRuntime(11193): 	at android.view.View.resolvePadding(View.java:13757)

E/AndroidRuntime(11193): 	at android.view.ViewGroup.resolvePadding(ViewGroup.java:6344)

E/AndroidRuntime(11193): 	at android.view.View.initializeScrollbarsInternal(View.java:4849)

E/AndroidRuntime(11193): 	at android.view.View.<init>(View.java:4278)

E/AndroidRuntime(11193): 	at android.view.ViewGroup.<init>(ViewGroup.java:503)

E/AndroidRuntime(11193): 	at android.widget.FrameLayout.<init>(FrameLayout.java:115)

E/AndroidRuntime(11193): 	at android.widget.TimePicker.<init>(TimePicker.java:84)

E/AndroidRuntime(11193): 	at android.widget.TimePicker.<init>(TimePicker.java:80)

E/AndroidRuntime(11193): 	at android.widget.TimePicker.<init>(TimePicker.java:76)

E/AndroidRuntime(11193): 	... 29 more
</code></pre>

**Comment by brandleesee** [comment]
@premnirmal this seems like a duplicate...

**Comment by premnirmal** [comment]
Yup. This has been fixed in https://github.com/premnirmal/StockTicker/pull/108
