### ISSUE TITLE
Widget refresh fails

### ISSUE THREAD

**Issue by webmihir** [premnirmal/StockTicker#81]
Widget refresh stopped working as of 5/20. Force refresh using the refresh button on widget, as well as pull-to-refresh within the app do not with either.

**Comment by Spqr753** [comment]
Agreed, refresh is failing. I have deleted cache and force restart as well.

**Comment by Spqr753** [comment]
Agreed, refresh is failing. I have deleted cache and force restart as well.

**Comment by will76** [comment]
+1 still not refresing :(. This is the best stock widget on Android.

**Comment by rs410ga** [comment]
Because it didn't refresh all day yesterday I mistakenly assumed it was Memorial Day.

**Comment by premnirmal** [comment]
The azure server was down, this was fixed last night, should be working now.

**Comment by terragit** [comment]
Thank you

**Comment by g4570n** [comment]
Refresh is failing again

**Comment by will76** [comment]
It's fine here. Amazing app.
