### ISSUE TITLE
No update on F-Droid since January '19

### ISSUE THREAD

**Issue by HawkEy33** [premnirmal/StockTicker#83]
[Latest Version on F-Droid is 3.0.4 from 7.January 2019](https://f-droid.org/de/packages/com.github.premnirmal.tickerwidget/)
[F-Droid Wiki](https://f-droid.org/wiki/page/Stocks_Widget) even stopped before that, no info why latest version's aren't built.
Anyone know what's the issue?

**Comment by premnirmal** [comment]
This is a question for F-Droid
