### ISSUE TITLE
Delete one single Widget

### ISSUE THREAD

**Issue by BlueEyesOnly** [premnirmal/StockTicker#88]
Hi, 
How can I delete one  single unsused widget from the list without deleting all widgets in the app with the "Clear app data" in the settings menu ?
Sometimes widgets are created by mistakes and stay there empty of data, I would like to be able to clean this list.
I really like this app and use it all day long.

Thx a lot.

**Comment by premnirmal** [comment]
Hello - thanks for your feedback.

Widgets created in the launcher and not the StocksWidget app, so you must delete it from the launcher that contains the widget. The app doesn't have permission to delete widgets from the home screen
