### ISSUE TITLE
Display total holdings

### ISSUE THREAD

**Issue by augustoteixeira** [premnirmal/StockTicker#90]
It would be very valuable to see somewhere the total amount of holdings (summing all stocks).

Right now one can see the holdings for each separate stock and some them up on a calculator, but this is far from practical. For me, "total holdings" is the most valuable information to help understand my position.

**Comment by jurgen178** [comment]
Same here. I have added a Total Holdings.
Let me know what you think. I have a PR ready.

![Screenshot_20200524-162402](https://user-images.githubusercontent.com/17816003/82767394-1e017780-9ddc-11ea-9101-c47598488f68.png)

**Comment by premnirmal** [comment]
@jurgen178 thank you for showing the prototype. Feel free to open the PR and I will review the change

**Comment by premnirmal** [comment]
Addressed in #131

**Comment by ThomasWaldmann** [comment]
Close issue?
