### ISSUE TITLE
Updates in non-US timezone

### ISSUE THREAD

**Issue by aureq** [premnirmal/StockTicker#94]
Hi,

This is a really cool widget. I live in Australia and noticed that the widget stops refresh during the weekend. However, my Saturday means it's still Friday in the US and financial markets are still active, yet the widget stops refreshing. The leads to inaccurate information being displayed until Monday clocks in.

Thank you.

**Comment by premnirmal** [comment]
That's a good point, the app never considered users in such time zones. This is fixed in https://github.com/premnirmal/StockTicker/pull/95. Thanks for reporting @aureq
